name: 🎯 Feature Request
description: Suggest an idea for this project
title: "FR: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a feature request!
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem, what you want to happen, and the context related to this request will help us understand and proceed in the right direction.
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
