name: Test Only

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  call-standard-test:
    name: Standard Test
    uses: hyeoncheon/.github/.github/workflows/go-test.yml@latest
    secrets: inherit
