name: Standard Go Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  dependency-review:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v1

  standard-go-test:
    name: go${{ matrix.go-version }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - "1.16"
          - "1.17"
          - "1.18"
        os:
          - "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          env
          go list
          go test -v -race -cover ./...
