name: Standard Go Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v1

  standard-go-test:
    needs: dependency-review
    name: Go v${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.16.x"
          - "1.17.x"
          - "1.18.x"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: |
          env
          go list
          go test -v -race ./...
